kind: pipeline
type: docker
name: default

steps:
- name: hello
  image: alpine:latest
  commands:
  - echo "Hello from Drone CI"
  - echo "Running tests..."
  - echo "Tests completed successfully"

- name: test
  image: python:3.9-alpine
  commands:
  - pip install -r requirements.txt
  - python -m pytest test_app.py -v
  - echo "Python tests completed"

- name: deploy
  image: alpine:latest
  commands:
  - echo "Deploying application..."
  - echo "Deployment completed successfully"
  when:
    branch:
    - main